### PR TITLE
Fix #21: Fix importing without having to change system path manually.

### LINKED ISSUE #21: ModuleNotFoundError
Having ModuleNotFoundError while running the command 

`python parsers/messenger.py --own-name "John Doe"`

There's __ init __.py in _parsers_ subdirectory, still facing this issue.
 
`Traceback (most recent call last):
  File "parsers/messenger.py", line 11, in <module>
    from parsers import log
ModuleNotFoundError: No module named 'parsers'`

### PR DESCRIPTION
**Pull request by hundredrab**

### CODE REVIEW

**Comment by hundredrab** [comment]
Hey @MasterScrat, Could you take a look at this when you get the time? Thanks and cheers!

**Comment by hundredrab** [comment]
Awesome :grin:

**Comment by MasterScrat** [comment]
Works for me, but I'm not sure how :-/ And IntelliJ complains about the imports.
How did you come up with this?

**Comment by hundredrab** [comment]
Basically hangouts.py is inside parsers/ so importing from parsers/ doesn't make sense to the program. If you do relative imports, they have to be in the place you said they are. 

logging shouldn't be imported from __init__ this way, but logging should be done in each file individually. Is that why your IDE is complaining?

**Comment by MasterScrat** [comment]
This fix has been integrated as part of the latest update!

**Pull request closed without merging**
